---
title: Configuration
description: Applies some configurations
privilege: TrustedInstaller
actions:

    # Necessary to refresh start menu entries, etc. (Thanks to SucklessWindows)
  - !appx: {operation: clearCache, name: '*Client.CBS*'}
  - !appx: {operation: clearCache, name: '*Windows.Search*'}
  - !appx: {operation: clearCache, name: '*TCUI*'}
    # Workaround for KGL versions to match (Thanks to SucklessWindows)
  - !appx: {operation: clearCache, name: '*XboxGameCallableUI*'}
  - !appx: {operation: clearCache, name: '*XboxGameOverlay*'}
  - !appx: {operation: clearCache, name: '*XboxGamingOverlay*'}
  - !appx: {operation: clearCache, name: '*XboxIdentityProvider*'}
  - !appx: {operation: clearCache, name: '*XboxSpeechToTextOverlay*'}
